version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    # no limit :)
    open-pull-requests-limit: 30
    ignore:
      # Ignore some updates to the 'assertj' package
      # Ignore only new versions for >= 3.x
      - dependency-name: "org.assertj:assertj-core"
        versions: ">= 3.0.0"
      # Ignore updates to the 'guava' package
      # found no way to instead integrate listenablefuture/9999.0-empty-to-avoid-conflict-with-guava
      - dependency-name: "com.google.guava:guava"
      # Ignore updates to the 'jts-core' package
      # jts-core 1.17.0 includes a API breaking change not supported by VTM
      - dependency-name: "org.locationtech.jts:jts-core"
